# Generated by Django 4.1.3 on 2022-12-02 11:35

import cars.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True,
                 upload_to=cars.models.upload_image_book)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
