# Generated by Django 4.1.3 on 2022-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='kilometers',
            field=models.IntegerField(default=85000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=85000, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
